### ISSUE TITLE
took a screenshot of my problem

### ISSUE THREAD

**Issue by curtiola** [Ed0n3/edBotYu#2]
![screenshot_2017-12-24-03-08-12](https://user-images.githubusercontent.com/16383836/34325738-d87480ea-e857-11e7-86c9-84df1ae60a55.png)

Any assistance would be appreciated!

**Comment by Ed0n3** [comment]
Sorry for the late reply. You are using the "master" branch, which was more like a test branch. The card reading functionality does not work properly.

The "working" branch should work, but this project is on ice, since the steam version is out and way easier to bot. (There are already some bots out)
